# Generated by Django 4.1.7 on 2023-05-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIF', models.CharField(max_length=9, unique=True)),
                ('nombreEmpresa', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=60)),
                ('datosContacto', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoReferencia', models.IntegerField(unique=True)),
                ('nombreModelo', models.CharField(max_length=16)),
                ('marca', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('precioTotal', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionPedidos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField(unique=True)),
                ('precio', models.FloatField()),
                ('nombre', models.CharField(max_length=16)),
                ('descripcion', models.CharField(max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionPedidos.categoria')),
                ('componente', models.ManyToManyField(to='appGestionPedidos.componente')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionPedidos.pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionPedidos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(through='appGestionPedidos.ProductoPedido', to='appGestionPedidos.producto'),
        ),
    ]
