# Generated by Django 4.1.7 on 2023-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precioTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
